/**
 * 
 */
package distance.revision;

import java.util.ArrayList;
import java.util.List;

import language.BeliefState;

/**
 * @author sam_t
 *
 */
public abstract class StateScoreResults {
	
	//for showing which states were revised by in the UI
	protected BeliefState sentences;
	protected List<StateScore> scores;
	
	/**
	 * 
	 */
	public StateScoreResults(BeliefState sent) {
		this.sentences = sent;
		this.scores = new ArrayList<StateScore>();
	}

	
	public BeliefState getSentences() {
		return this.sentences;
	}
	
	public List<StateScore> getScores() {
		return this.scores;
	}
	
	public void addStateScore(StateScore ss) {
		this.scores.add(ss);
	}
	
	
	//min score
	//
//	public BeliefState scoreToBeliefState() {
//		
//	}
	
	
	/*
	 * Converts the BeliefState generated by the GeneralRevisionScore object into a RankingState object
	 * 
	 * @return
	 * 	RankingState result of min score values
	 */
//	public RankingState scoreToRank(ArrayList<Character> vocab) {
//		return new RankingState(scoreToBeliefState(), vocab);
//	}
	
	public abstract void setResults() throws Exception;
}
